services:
  meetingroomrezervation:
    image: hknyvzz/meetingroomrezervation:latest
    build:
      context: .
      dockerfile: MeetinRoomRezervation/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - vadi_network

  mongo:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - "27017:27017"
    networks:
      - vadi_network
    volumes:
       - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
       - ./volumes/mongo:/data/db
    command: [--auth]

networks:
  vadi_network:
    driver: bridge