services:
  meetingroomrezervation:
    build:
      context: .
      dockerfile: MeetinRoomRezervation/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017/BilisimVadisi
    depends_on:
      - mongodb
    networks:
      - bilisimvadisi-network

  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bilisimvadisi-network
    command: mongod --bind_ip_all

networks:
  bilisimvadisi-network:
    driver: bridge

volumes:
  mongodb_data:
